### ISSUE TITLE
Documentation mentions dust.Context.base but Context is no longer exposed

### ISSUE THREAD

**Issue by mihalik** [akdubya/dustjs#1]
The documentation mentions creating a base Context a couple times:  

// Set up a base context with global helpers
var base = dust.Context.base({
  sayHello: function() { return "Hello!" }
});

But the code to expose the Context was removed a few days ago according to the history so this code does not work.  Should the documentation be changed?  Or should the ability to create a base Context be exposed with some other method?

**Comment by akdubya** [comment]
Thanks for pointing that out. I absolutely meant to include a top-level method for creating base contexts. Will fix.

**Comment by akdubya** [comment]
dust.Context.base -> dust.makeBase (closed by b1e0d77dea6e437e191674ad2c33d524dc953757)
