### ISSUE TITLE
Helpers don't support . syntax

### ISSUE THREAD

**Issue by stonecobra** [akdubya/dustjs#14]
When I push a native object onto the stack, I can navigate with dot syntax, for example:
{user.FirstName}
If I make user a helper function, like this in dust.makeBase:
user: function(chunk, context){
    var req = context.get('req');
    return req.session.user;
}
and then try the same, it doesn't work:
{user.FirstName}
but this does work:
{#user}{FirstName}{/user}

Am I doing something wrong?

**Comment by akdubya** [comment]
Nope. Dot syntax is intended to allow convenient access to plain nested objects.
