### ISSUE TITLE
How do I output '{' in a template?

### ISSUE THREAD

**Issue by stonecobra** [akdubya/dustjs#15]
There doesn't seem to be an escape for { or }.  How would you use dust to generate JSON?

**Comment by GCheung55** [comment]
In yout template {~lb} and {~rb} is { and }, respectively. So if you're trying to ouput json in template form:

var json_tpl = '{~lb}'name': {name}, 'someText': {text}{~rb}';

**Comment by stonecobra** [comment]
Thanks for the tip! Missed that in the code and docs somehow.  Makes sense now reading the pegjs code.
