### ISSUE TITLE
Consider redesigning docs in a single column

### ISSUE THREAD

**Issue by callumlocke** [akdubya/dustjs#69]
I find the [akdubya.github.io/dustjs](http://akdubya.github.io/dustjs) page difficult to read/scan because of the unconventional layout. Side-by-side columns that are taller than the viewport are confusing and disorienting; that's why no one uses them. It's harder to jump between sections when there are two dimensions to think about. The page is seriously inaccessible for people who have difficulty with reading comprehension. Please consider redesigning it as a normal, linear document. I've tried to check out dust on several occasions (I keep hearing good things about it) but I always give up after a few minutes because I just can't follow the docs.

**Comment by sethkinast** [comment]
You might try LinkedIn's new docs at http://dustjs.com

**Comment by callumlocke** [comment]
Thanks!
